version: "3"
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            # - 3000:80
            - 80:80
            - 443:443
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

    app:
        build: .
        restart: always
        # ports:
        #     - 3000:3000
        env_file:
            - ./app.env
        depends_on:
            - mongodb
        deploy:
            replicas: 4
            restart_policy:
                condition: any
            update_config:
                parallelism: 2
                delay: 10s
                failure_action: rollback

    mongodb:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        volumes:
            - mongodb-data:/data/db

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
            ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
            ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
        depends_on:
            - mongodb

volumes:
    mongodb-data:
